### ISSUE TITLE
How to proceed with required delegates?

### ISSUE THREAD

**Issue by danipralea** [mbalex99/RxSwiftMapViewDelegateProxyExample#1]
Hi and thank you for your work here!
Any idea how to treat with required delegates? (in your example the delegates for MKPMapView are all optional) 
I'm currently being presented with an error if I do not implement them. And if I do, the empty implementation gets called instead.

Thanks!

**Comment by mbalex99** [comment]
@danipralea Hey required delegates have to be encapsulated check out RxDataSources. 

As you can see you create a new object (it's a wrapped up API around UITableView cellForRowAtIndexPath). That's a required method.

We can't just rx_requireMethod and then have a returner function. 

There's no straight forward way to do this. You can of course just implement the required methods. The listener methods (which are usually almost always optional) can be rx-ified.
